# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joyería Moon
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Joyería Moon
address_line: Via Ludovisi 39-45, Rome, 54267, Italy
telephone_number: 5535 625 678
fax_number: 557 9867 123
company_email: joyeriamoon@gmail.com
google_map: https://www.google.com.mx/maps/place/Joyer%C3%ADas+Bizzarro+Encuentro+Ocean%C3%ADa/@19.4400916,-99.0943372,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipOXIoEBbYVfQqHPV5NW5pFx-N7zIHOg3W9O7oBz!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipOXIoEBbYVfQqHPV5NW5pFx-N7zIHOg3W9O7oBz%3Dw152-h86-k-no!7i4032!8i2268!4m10!1m2!2m1!1sjoyer%C3%ADa+moon!3m6!1s0x85d1fb3b25e71b5b:0x61d0504330be17e0!8m2!3d19.4399081!4d-99.0939757!10e5!16s%2Fg%2F11rcvy5lb1

# Social Link
facebook_link: https://www.facebook.com/dana.lorenzo.944
twitter_link: https://twitter.com/mont_g09
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
